name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
            go-version: '1.22'

      - name: Build app
        run: ./scripts/buildprod.sh
      
      - name: Set up gcloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Build image
        run: gcloud builds submit --tag europe-north1-docker.pkg.dev/notely-433208/notely-ar-repo/notely-image:${{ github.run_number }} .

      - name: Install goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Run the migrations
        run: ./scripts/migrateup.sh

      - name: Deploy to Cloud Run
        run: gcloud run deploy notely --image europe-north1-docker.pkg.dev/notely-433208/notely-ar-repo/notely-image:${{ github.run_number }} --region us-central1 --allow-unauthenticated --project notely-433208 --max-instances=4